---
title: "Домашка №5"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    highlight: pygments
editor_options: 
  chunk_output_type: console
---
---

### Правила игры

Пятая домашка нацелена на парсинг.

1. Домашка оформляется в R Markdown или в обычном скрипте.
2. Подгрузите все нужные вам пакеты в самом начале в одном чанке.

---

### Пакеты

Подгрузим пакеты, которые понадобятся вам для решения задачи.

```{r warning=FALSE, message=FALSE}
library(rvest)
library(tibble)
library(dplyr)
library(ggplot2)
```

### Задание

__Цель__: вам нужно спарсить информацию с сайта.

* _Вариант №1._ Вы можете сами выбрать интересующий вас сайт и спарсить его. Но вы должны спарсить не одно какое-то значение (например, цену за один товар), а какой-то блок информации.

* _Вариант №2._ Сделать что-то из следующего:
  + Взять сайт ["беру"](https://beru.ru/) и спарсить какой-то запрос (например, Iphone).
  + Выкачать информацию о топ-250 фильмах с [кинопоиска](https://www.kinopoisk.ru/top/).
  + Написать парсер, который будет выкачивать количество просмотров видеоролика c YouTube. Парсер может собирать информацию какждые 10 минут. А потом можно будет нарисовать временной ряд просмотров.
  + С предыдущими заданиями нужно попотеть. Если идет тяжко, то возьмите парсер Avito, который мы делали на паре и улушите его. Сделайте функцию, которая будет принимать название запроса, а выдавать информацию по каждому товару в виде data frame.
  
Парсинг это сложно. Вас будут пытаться блочить, ставьте `Sys.sleep`, чтобы этого избежать. Если есть желание и время, то используйет `RSelenium`. 
