---
title: "Введение в R, переменные и массивы: задания"
output: 
  html_document:
    css: ../css/style.css
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
    highlight: pygments
editor_options: 
  chunk_output_type: console
---
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Задачи для работы на семинаре 

### Задание №1

Вычислите значение выражения $\cos(\frac{\pi}{4})$. Результат округлите до двух знаков после запятой.

### Задание №2

Запустите следующий код. `round(pi; 3)`. Работает ли он, если нет, то почему?

### Задание №3

Сложите какое-то число с `NA`. Что получилось и почему так получилось? Попробуйте повыполнять другие арифметические операции. Что-то изменилось? Что будет, если сложить `NA` с `NA`? 

### Задание №4

Создайте переменную `n` равную 3. После чего создайте переменную `a` равную $n^n$. После чего присвойте переменной `n` новое значение равное 4. Изменится ли значение переменной `a`?

### Задание №5

Создайте строковую переменную `name` равную "Alsu". Умножьте эту переменную на 3, что получится? Что за тип у переменной `name`? 

### Задание №6

У вас имеются 2 переменные, как поменять их значения местами? Например, у вас имеются переменная `a` равная 5 и переменная `b` равная 10. Нужно, чтобы теперь в переменной `a` хранилось значение 10, а в переменной `b` хранилось значение 5.

### Задание №7

Выведите последний элемент массива и его позицию. 

### Задание №8

Создайте массивы четных и нечетных чисел от 1 до 100.

### Задание №9

Создайте массив, состоящий из 100 единиц. 

### Задание №10

Создайте массив, состоящий из 10 случайных двухзначных чисел. Посчитайте его сумму. Выполните весь код еще раз. Поменялся ли ответ? 

### Задание №11

Создайте два массива, состоящих из четырех случайных чисел от 1 до 10. Сложите эти два массива. Теперь замените 3ий элемент одного из массивов на `NA`. Сложите массивы еще раз. Что изменилось? Теперь добавьте элемент равный 100 в начало массива и сложите массивы в третий раз. Что случилось теперь? 

### Задание №12

Гонщик движется по кольцевой дороге, длина которой 4км. Сколько кругов он проедет через $n$ метров ($n > 0$)? Если гонщик не доехал круг, то сколько метров нужно ему еще проехать до финиша?

### Задание №13

Определите, сколько часов (число от 0 до 23) и минут (число от 0 до 59) будут показывать часы через $t$ минут ($t > 0$) после начала суток. 

### Задание №14

В университете решили набрать три новых группы для занятий по программированию. В первой группе -- $n_1$ человек, во второй -- $n_2$, в третьей -- $n_3$. Сколько нужно будет закупить компьютерных столов для студентов, если известно, что за одним столом могут находиться не более 2х человек и что занятия студентов проходят в одно время? 










